### ISSUE TITLE
Inquiry... Is it possible to modify the contrast?

### ISSUE THREAD

**Issue by GL24TZ** [jazz-soft/char-lcd#4]
Hello!! I can't find a way to achieve a contrast like the one shown in the image. How can I achieve that? Thank you in advance, and I apologize for my lack of experience

![{0345EB9A-937E-45EB-B16D-916C49C007E5}](https://github.com/user-attachments/assets/b7c4a270-7879-46ef-84c4-fb5ad85d52f8)

**Comment by jazz-soft** [comment]
You can create the object with additional parameters. e.g. `{ ..., off: '#cd2', on: '#143' }`
